# Generated by Django 2.2.10 on 2020-03-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_image', models.ImageField(upload_to='')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_description', models.TextField()),
            ],
        ),
    ]
