# Generated by Django 2.2.10 on 2020-03-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat_image',
            field=models.ImageField(upload_to='static/categories/images'),
        ),
    ]
