# Generated by Django 2.2.10 on 2020-03-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200321_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat_image',
            field=models.ImageField(upload_to='items/static/categories/images'),
        ),
    ]
