# Generated by Django 2.2.10 on 2020-03-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_price',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
