# Generated by Django 2.2.10 on 2020-03-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200321_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_price',
            field=models.IntegerField(),
        ),
    ]
