# Generated by Django 2.2.10 on 2020-03-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200322_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_description',
            field=models.TextField(default=None),
        ),
    ]
