# Generated by Django 2.2.10 on 2020-05-23 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caremain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'a'), ('rejected', 'r'), ('pending', 'p'), ('completed', 'c'), ('active', 'A')], max_length=50)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='givers', to=settings.AUTH_USER_MODEL)),
                ('careseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seekers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CareSeeker',
        ),
    ]
