# Generated by Django 2.2.10 on 2020-05-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caremain', '0003_carerequests_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerequests',
            name='end_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carerequests',
            name='start_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
