# Generated by Django 2.2.10 on 2020-06-26 16:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caremain', '0004_auto_20200529_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamount', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 6, 26, 21, 48, 36, 422320))),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tgiver', to=settings.AUTH_USER_MODEL)),
                ('careseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tseeker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
