# Generated by Django 2.2.10 on 2020-04-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
