# Generated by Django 2.2.10 on 2020-04-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_name',
        ),
    ]
