# Generated by Django 2.2.10 on 2020-05-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_elder',
            field=models.BooleanField(blank=True),
        ),
    ]
