# Generated by Django 2.2.10 on 2020-05-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200513_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_elder',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
