# Generated by Django 2.2.10 on 2020-05-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caremainapp', '0003_carerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareRequest',
        ),
    ]
