# Generated by Django 2.2.10 on 2020-05-18 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caremainapp', '0005_carerequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carerequest',
            unique_together={('request_by', 'request_to')},
        ),
    ]
