# Generated by Django 2.2.10 on 2020-05-18 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caremainapp', '0006_auto_20200518_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerequest',
            name='request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
