# Generated by Django 2.2.10 on 2020-05-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_caregiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiver',
            old_name='earnig',
            new_name='earning',
        ),
    ]
